### ISSUE TITLE
mac os x binaries

### ISSUE THREAD

**Issue by DenDunn** [Maijin/Workshop2015#2]
Hello,

it would be great to add binaries for mac os, please.

Thanks!

**Comment by XVilka** [comment]
You mean dissecting them as an examples?

**Comment by DenDunn** [comment]
I mean, there are compiled binaries for win32, linux and powerPC in the tar (IOLI-crackme.tar.gz), but no compiled binaries for OSX, so it would be convenient if binaries for mac is added(because we have OSX version of the framework). Otherwise mac users(me🙃) need to set up virtual machine to accomplish the IOLI crackme chapter.

Thank you.

**Comment by Maijin** [comment]
I know, but the guy who has created them doesn't have source anymore

**Comment by DenDunn** [comment]
I see, ok, thanks for answer, and all the best.
